### ISSUE TITLE
Allow referring to a capture via `capture.<key>`

### ISSUE THREAD

**Issue by rhrazdil** [nmstate/nmpolicy#109]
It may be more user-friendly and less error prone to refer to captured state via `capture` identity, instead of having to use a `pipe`.

Consider the following nmpolicy snippet:
```
spec:
  capture:
    ethernets: interfaces.type=="ethernet"
    ethernets-up: capture.ethernets | interfaces.state=="up"
```

It would be nice if the pipe wasn't required to access a captured state, and allow referring to it directly by a path, like so:
```
spec:
  capture:
    ethernets: interfaces.type=="ethernet"
    ethernets-up: capture.ethernets.interfaces.state=="up"
```
