### ISSUE TITLE
Not failing on non-existing path in the capture

### ISSUE THREAD

**Issue by AlonaKaplan** [nmstate/nmpolicy#73]
```
capture:                                                                      
    vlan-204: interfaces.lldp.neighbors.ieee-802-1-vlans.vid==204
```

state
```
- ethernet:
          auto-negotiation: true
          duplex: full
          speed: 10000
        ipv4:
          address: []
          auto-dns: true
          auto-gateway: true
          auto-route-table-id: 0
          auto-routes: true
          dhcp: true
          enabled: true
        ipv6:
          address: []
          autoconf: false
          dhcp: false
          enabled: false
        lldp:
          enabled: true
          neighbors:
          - - system-name: sw01-access-f1.example.com
              type: 5
            - system-description: 'Juniper Networks, Inc'
              type: 6
            - system-capabilities:
              - MAC Bridge component
              - Router
              type: 7
            - _description: MAC address
              chassis-id-type: 4
              type: 1
            - _description: Interface name
              port-id: xe-0/0/17
              port-id-type: 5
              type: 2
            - ieee-802-1-vlans:
              - name: vlan-204
                vid: 204
              - name: vlan-205
                vid: 205
              subtype: 3
              type: 127
            - ieee-802-3-mac-phy-conf:
                autoneg: false
                operational-mau-type: 0
                pmd-autoneg-cap: 32768
              oui: 00:12:0f
              subtype: 1
              type: 127
            - management-addresses:
                address-subtype: ipv4
                interface-number: 0
                interface-number-subtype: 1
              type: 8
            - ieee-802-3-max-frame-size: 9216
              oui: 00:12:0f
              subtype: 4
              type: 127
        mtu: 1500
        name: ens1f0
        state: up
        type: ethernet
```

Currently, nmpolicy will fail resolving this capture since not all the neighbor entries have the "ieee-802-1-vlans" key.

 The implementation should be changed not to fail if at least one of the entries in a list has the required path.
